env:
    node: true
    es6: true
    mocha: true
parserOptions:
    ecmaFeatures: {jsx: true}
rules:
    semi: [2, always]
    comma-style: [1, last]
    quotes: [2, single]
    key-spacing: [2]
    comma-spacing: [2, {before: false, after: true}]
    keyword-spacing: [2, {before: true, after: true}]
    space-before-blocks: [2, always]
    eol-last: 2
    no-extra-semi: 1
    no-constant-condition: 2
    no-extra-boolean-cast: 2
    use-isnan: 2
    no-undef-init: 2
    camelcase: 2
    no-mixed-spaces-and-tabs: 2
    no-const-assign: 2
    no-func-assign: 2
    no-else-return: 1
    no-obj-calls: 2
    valid-typeof: 2
    no-unused-vars: 1
    object-curly-spacing: 2
    block-spacing: 1
    comma-dangle: 0
    array-bracket-spacing: 1
    space-before-function-paren: [error, {named: never, asyncArrow: always, anonymous: always}]
    no-extra-bind: 1
    no-var: error
    arrow-spacing: [error, {before: true, after: true}]
    arrow-body-style: [error, as-needed]
    no-empty-function: [error, {allow: [arrowFunctions, constructors]}]
    indent: [error, 4]
    no-irregular-whitespace: 2
settings:
    import/resolver: {node: {extensions: [.coffee, .js, .jsx]}}
    import/ignore: [node_modules]
