.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. compchain_qt test_compchain_qt
clean: FORCE
	$(MAKE) -C .. compchain_qt_clean test_compchain_qt_clean
check: FORCE
	$(MAKE) -C .. test_compchain_qt_check
compchain-qt compchain-qt.exe: FORCE
	 $(MAKE) -C .. compchain_qt
